#!/bin/bash
set -fue

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# blocklist.de
URL=https://lists.blocklist.de/lists/all.txt

# https://www.spamhaus.org/drop/
EDROP=https://www.spamhaus.org/drop/edrop.txt
DROP6=https://www.spamhaus.org/drop/dropv6.txt

CF4=https://www.cloudflare.com/ips-v4
CF6=https://www.cloudflare.com/ips-v6

# huge address spaces but still smaller than the wholes inet
LE6="2600:1F00::/24 2600:1F14::/35 2600:3000::/29"

TEMP=`mktemp -d`

function cleanup {
  rm -rf ${TEMP}
  ipset destroy block6-temp &>/dev/null || true
  ipset destroy block-temp &>/dev/null || true
}
trap cleanup ERR

cd "$TEMP"

wget --timeout=60 -q ${URL} || touch all.txt
wget --timeout=60 -q ${EDROP} || touch edrop.txt
wget --timeout=60 -q ${DROP6} || touch dropv6.txt
wget --timeout=60 -q ${CF4} || touch ips-v4
wget --timeout=60 -q ${CF6} || touch ips-v6

cat edrop.txt dropv6.txt | grep -v '^;' | awk '{print $1}' > spamhaus.txt

ipset create block-temp hash:net family inet hashsize 2048 maxelem 65536
ipset create block6-temp hash:net family inet6 hashsize 2048 maxelem 65536

for ip in $(cat all.txt | grep -v : | sort | uniq)
  do
        ipset add block-temp $ip
done

for ip in $(cat spamhaus.txt | grep -v : | sort | uniq)
  do
        ipset add block-temp $ip
done


for ip in $(cat all.txt | grep : | sort | uniq)
  do
        ipset add block6-temp $ip
done

for ip in $(cat spamhaus.txt | grep : | sort | uniq)
  do
        ipset add block6-temp $ip
done

ipset swap block-temp block4
ipset swap block6-temp block6

ipset flush block-temp
ipset flush block6-temp

for ip in $(cat ips-v4)
  do
        ipset add block-temp $ip
done

for ip in $(cat ips-v6) ${LE6}
  do
        ipset add block6-temp $ip
done

ipset swap block-temp cf4
ipset swap block6-temp cf6

cleanup
