---
image: debian

before_script:
  - apt update
  - apt install -y curl jq openssh-client python3-pip git rsync g10k
  - pip3 install yq

.template1: &template1 |
  eval $(ssh-agent -s)
  echo "$SSH_KEY_PUPPET" | tr -d '\r' | ssh-add - > /dev/null
  install -m 0700 -d ~/.ssh
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gfa/hieradata.git -b ${CI_COMMIT_REF_NAME} hieradata \
  || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gfa/hieradata.git -b master hieradata
  g10k -cachedir g10k-cache -verbose -puppetfile Puppetfile

cache:
  paths:
    - g10k-cache

production:
  resource_group: $CI_COMMIT_REF_SLUG
  script:
    - *template1
    - HOSTS=$(cat hieradata/inventory.yaml| yq '.groups[].targets[]' | sed 's/"//g')
    - |
      for host in ${HOSTS}
        do
          bash puppet-apply --show_diff $host || curl -s -X POST \
            -F "title=puppet failed to apply on $host ref: $CI_COMMIT_REF_NAME" \
            -F "message=$(date)" \
            -F "priority=$GOTIFY_PRIORITY" \
            "${GOTIFY_URL}?token=${GOTIFY_TOKEN}"
      done
  artifacts:
    paths:
      - logs/debug.log
    expire_in: 1 week
    when: always
  variables:
    BOLT_PROJECT: /builds/gfa/puppet-bolt
  only:
    refs:
      - master
      - scheduled

testing:
  resource_group: $CI_COMMIT_REF_SLUG
  script:
    - *template1
    - |
      for host in ${TEST_HOSTS}
        do
          bash puppet-apply --show_diff $host || curl -s -X POST \
            -F "title=puppet failed to apply on $host ref: $CI_COMMIT_REF_NAME" \
            -F "message=$(date)" \
            -F "priority=$GOTIFY_PRIORITY" \
            "${GOTIFY_URL}?token=${GOTIFY_TOKEN}"
      done
  artifacts:
    paths:
      - logs/debug.log
    expire_in: 1 week
    when: always
  variables:
    BOLT_PROJECT: /builds/gfa/puppet-bolt
  except:
    refs:
      - master
      - scheduled
      - /^wip-.*$/i
