---
image: debian:bullseye

before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -y curl jq openssh-client python3-pip git rsync g10k hiera-eyaml moreutils nullmailer bsd-mailx screen sysvinit-utils
  - pip3 install yq

.template1: &template1 |
  eval $(ssh-agent -s)
  echo "$SSH_KEY_PUPPET" | tr -d '\r' | ssh-add - > /dev/null
  install -m 0700 -d ~/.ssh
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gfa/hieradata.git -b ${CI_COMMIT_REF_NAME} hieradata \
  || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gfa/hieradata.git -b master hieradata
  cp -f hieradata/ssh_config ~/.ssh/config
  ssh -o "ExitOnForwardFailure=yes" -o "ServerAliveInterval=55" -L 127.0.0.1:10025:127.0.0.1:25 $SMTP_SERVER -fNn

cache:
  paths:
    - g10k-cache
    - facts_db

production:
  resource_group: $CI_COMMIT_REF_SLUG
  script:
    - *template1
    - HOSTS=$(cat hieradata/infrastructure.yaml| yq '.infrastructure.hosts | keys' | sed -E 's/"|,|\[|\]//g; s/^ *//; s/ *$//; /^$/d')
    - |
      for host in ${HOSTS}
        do
          if [[ ${host::-9} == ".lan.home" ]]; then
            echo 127.0.0.1 $host >> /etc/hosts
          fi
          ./puppet-apply -t --show_diff $host &
      done
    - sleep 5m

  artifacts:
    paths:
      - logs/
      - facts_db/
    expire_in: 1 week
    when: always
  variables:
    BOLT_PROJECT: /builds/gfa/puppet-bolt
  only:
    refs:
      - master
      - scheduled
