---
image: debian

before_script:
  - apt update
  - apt install -y curl jq
  # I don't want more than one copy of the pipeline running
  # https://gitlab.com/gitlab-org/gitlab-foss/issues/41560
  # https://gitlab.com/gitlab-org/gitlab-foss/issues/20481

  - |
    printf '\nWaiting...\n'
    while true; do
      OLDEST_JOB=$(curl -sS --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs?scope=running" | jq '.[].id' | sort -n -r | tail -1)
      if [ "${OLDEST_JOB}x" = "${CI_JOB_ID}x" ]; then
        printf '\nReady!\n'
        break
      else
        printf '.'
        sleep 10
      fi
    done

  # resuming normal flow

.template1: &template1 |
  apt install -y openssh-client ruby-dev gems build-essential python3-pip git
  pip3 install yq
  gem install bundler
  bundler install
  mkdir -p ~/.puppetlabs/bolt/ logs
  echo -e "disabled: true" > ~/.puppetlabs/bolt/analytics.yaml
  mv -f .bolt.yaml.gitlab bolt.yaml
  bolt puppetfile install
  eval $(ssh-agent -s)
  echo "$SSH_KEY_PUPPET" | tr -d '\r' | ssh-add - > /dev/null
  install -m 0700 -d ~/.ssh
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gfa/hieradata.git hieradata
  ln -s hieradata/keys .

production:
  script:
    - *template1
    - HOSTS=$(cat hieradata/inventory.yaml | yq '.nodes[][]' | sed 's/"//g')
    - |
      for host in ${HOSTS}
        do
          bolt plan run base -n $host || curl -s -F "token=$PUSHOVER_KEY" \
            -F "user=$PUSHOVER_USER" -F "message=puppet failed to apply on $host" \
            https://api.pushover.net/1/messages.json
      done
  artifacts:
    paths:
      - logs/debug.log
    expire_in: 1 week
    when: always
  only:
    refs:
      - master
      - scheduled

testing:
  script:
    - *template1
    - HOSTS=$(cat hieradata/inventory.yaml | yq '.nodes[][]' | sed 's/"//g')
    - |
      for host in ${TEST_HOSTS}
        do
          bolt plan run base -n $host || curl -s -F "token=$PUSHOVER_KEY" \
            -F "user=$PUSHOVER_USER" -F "message=puppet failed to apply on $host ref: $CI_COMMIT_REF_NAME" \
            https://api.pushover.net/1/messages.json
      done
  artifacts:
    paths:
      - logs/debug.log
    expire_in: 1 week
    when: always
  except:
    refs:
      - master
      - scheduled
      - /^wip-.*$/i
