# frozen_string_literal: true

# rubocop:disable BlockLength
source ENV['GEM_SOURCE'] || 'https://rubygems.org' do
  # rubocop:enable BlockLength
  gem 'bcrypt_pbkdf', '~> 1'
  gem 'bolt', '~> 1'
  gem 'ed25519', '~> 1.2'
  gem 'gpgme'
  gem 'hiera-eyaml'
  gem 'hiera-eyaml-gpg'
  gem 'puppet', '~> 6'
  gem 'puppet-lint'
  gem 'puppet-lint-absolute_template_path'
  gem 'puppet-lint-classes_and_types_beginning_with_digits-check'
  gem 'puppet-lint-concatenated_template_files-check'
  gem 'puppet-lint-duplicate_class_parameters-check'
  gem 'puppet-lint-leading_zero-check'
  gem 'puppet-lint-legacy_facts-check'
  gem 'puppet-lint-no_erb_template-check'
  gem 'puppet-lint-no_file_path_attribute-check'
  gem 'puppet-lint-no_symbolic_file_modes-check'
  gem 'puppet-lint-param-docs'
  gem 'puppet-lint-resource_reference_syntax'
  gem 'puppet-lint-strict_indent-check'
  gem 'puppet-lint-template_file_extension-check'
  gem 'puppet-lint-top_scope_facts-check'
  gem 'puppet-lint-trailing_newline-check'
  gem 'puppet-lint-unquoted_string-check'
  gem 'puppet-lint-variable_contains_upcase'
  gem 'puppet-lint-version_comparison-check'
  gem 'puppet-lint-world_writable_files-check'
  gem 'puppetlabs_spec_helper'
  gem 'r10k'
  gem 'rspec-puppet'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
  gem 'yaml-lint'
end
