---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake ci:setup:rspec spec\""
Rakefile:
  unmanaged: true
Gemfile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true